icon_theme = "Papirus"
font = "JetBrains Mono,JetBrains Mono Medium"
size = [500, 280]
font_size = 15
background = "#2E3440"
border_color = "#2E3440"
border_radius = 30.0
border_width = 40.0

[rows.lines.default]
background = "#2E3440"
text_color = "#81A1C1"
padding = 5

[rows.lines.selected]
background = "#2E3440"
text_color = "#EBCB8B"
padding = 5

[scrollable]
scrollbar_width = 0
scroller_width = 0

[search.bar]
background = "#3B4252"
value_color = "#8FBCBB"
placeholder_color = "#8FBCBB"
border_color = "#3B4252"
selection_color = "#fcfbfb"
text_width = "fill"
border_radius = 30.0
border_width = 45.0

[search]
background = "#2E3440"
height = 30