icon_theme = "Arc"
font = "JetBrains Mono,JetBrains Mono Medium"
size = [800, 280]
font_size = 18
background = "#2E3440"
border_color = "#00000000"
border_radius = 0.0
border_width = 10.0

[rows.lines.default]
background = "#2E3440"
text_color = "#81A1C1"
padding = 5

[rows.lines.selected]
background = "#2E3440"
text_color = "#EBCB8B"
padding = 5

[scrollable]
scrollbar_width = 0
scroller_width = 0

[search.bar]
background = "#3B4252"
value_color = "#8FBCBB"
placeholder_color = "#8FBCBB"
border_color = "#00ff00ff"
selection_color = "#fcfbfbff"
text_width = "fill"

[search]
background = "#3B4252"
height = 30