name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: SemVer release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - run:
          cargo install cargo-edit

      - name: SemVer release
        id: release
        uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'
          release: true

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build VuePress site
        working-directory: ./docs/website
        run: pnpm install && pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          domain: docs.onagre.dev
          target_branch: gh-pages
          build_dir: docs/website/src/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}